#!/usr/bin/env python3

import datetime
import errno
import json
import os
from sys import stderr
import urllib.error
import urllib.parse
import urllib.request

if __name__ == '__main__':
    home = os.getenv('HOME')

    with open(os.path.join(home, '.timesync'), 'r') as config:
        config = json.load(config)

        project = input('Project: ')
        activities = [input('Activity: ')]
        while(input('More activities? [y/n] ') == 'y'):
            activities.append(input('Activity: '))

        duration = int(input('Time worked in seconds: '))
        issue_uri = input('Issue uri: ') or None

        d = datetime.datetime.now()
        month_worked = input('Month worked (format: 01): ')
        day_worked = input('Day worked (format: 31): ')
        year_worked = d.year

        if month_worked is "":
            month_worked = d.month

        if day_worked is "":
            day_worked = d.day

        date_worked = "{}-{}-{}".format(year_worked, month_worked, day_worked)

        note = input('Note: ')

        url = "{}/v1/times".format(config['server'])
        values = {
            'auth': {
                'username': config['username'],
                'password': config['password'],
            },
            'object': {
                'duration': duration,
                'user': config['username'],
                'project': project,
                'activities': activities,
                'issue_uri': issue_uri,
                'date_worked': date_worked,
                'notes': note
            }
        }

        data = json.dumps(values)
        data = str.encode(data)

        req = urllib.request.Request(
            url, data, {'Content-Type': 'application/json'})

        try:
            with urllib.request.urlopen(req) as response:
                print("Time successfully recorded!")
        except urllib.error.HTTPError as e:
            error_message = e.read()
            print(error_message, file=stderr)
            exit(errno.ENETDOWN)
        except urllib.error.URLError as e:
            print("Cannot connect to server!", file=stderr)
            exit(errno.ENETUNREACH)
